[libcxx] Bump __libcpp_version to 14 after branch
This was missed in 808b5d503e67f7f02cfdb2c005a30287dccff963
and caused test failures in the buildkite bots:
libcpp_version.pass.cpp:22:1:
error: static_assert failed due to requirement '14000 == libcpp_version'
"_LIBCPP_VERSION doesn't match __libcpp_version